name: SimplePipeline

on:
  push:
    branches: [ main ]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          echo "Running installation for dependencies..."
          npm install
      - name: Run Linting
        run: |
          echo "Running linting tests..."
          npm run lint
        env:
          CI: true
  securityCheck:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security Vulnerabilities
        run: |
          echo "Running security check for vulnerabilities... start"
          sleep 5s;
          echo "Running security check for vulnerabilities... 1"
          sleep 5s;
          echo "Running security check for vulnerabilities... 2"
          sleep 5s;
          echo "Running security check for vulnerabilities... 3"
          sleep 5s;
